version: '3.8'

services:
  cv-nginx:
    image: nginx:alpine
    container_name: cv-web
    ports:
      - "3000:80"   
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - cv-network

networks:
  cv-network:
    driver: bridge
